
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define a type for the slice state
interface CartState {
  isShown: boolean;
}

// Define the initial state using that type
const initialState: CartState = {
  isShown: false,
};

export const cartSlice = createSlice({
  name: "cart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  // Use the PayloadAction type to declare the contents of `action.payload`
  reducers: {
    showCart( 
      state: CartState,
      action: PayloadAction<boolean>
    ) {
        state.isShown = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {}
});

// reducers/actions go in here in order to import them into components
export const { showCart } = cartSlice.actions;

export default cartSlice.reducer;